blank_issues_enabled: false
contact_links:
  - name: Flutter ドキュメント
    url: https://docs.flutter.dev
    about: Flutter公式ドキュメントとガイド
  - name: Dart言語ツアー
    url: https://dart.dev/language
    about: Dart言語の機能について学ぶ
  - name: GitHub Copilot ドキュメント
    url: https://docs.github.com/en/copilot
    about: GitHub Copilotの効果的な使用方法を学ぶ